apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: json-server-api-hpa
  namespace: default
spec:
  minReplicas: 7
  maxReplicas: 15
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: json-server-api